name: autotest
on: page_build
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: autotests
    steps:
      - name: Trigger Autotests
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.CHARTJS_DEMO_AUTOTEST_RUN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'kuzanatoliy',
              repo: 'chartjs-demo-integration-tests',
              workflow_id: 'e2e.yml',
              ref: 'master'
            });
